### ISSUE TITLE
As a fan of The Weeknd, I want to be able to see the latest Tweets about the Weeknd, so that I can be up-to-date and see what people are saying about him and his work.

### ISSUE THREAD

**Issue by donuthole55** [vravila/MuseNews#9]
Estimated Time: 12 hours
Actual Time: 10 hours
Description: We want to add Tweets to the instance page of each artist. This way, when users load the page of an instance of an artist (e.g. The Weeknd's page), they will see information about the artist as well as the most recent tweets about the artist. This furthers Muse-News's goal of giving users interconnected and up-to-date information about music.

**Comment by kedaraman** [comment]
Estimated Time: 12 hours
Actual Time: 10 hours
Description: We want to add Tweets to the instance page of each artist. This way, when users load the page of an instance of an artist (e.g. The Weeknd's page), they will see information about the artist as well as the most recent tweets about the artist. This furthers Muse-News's goal of giving users interconnected and up-to-date information about music.
